// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADoRho8Z8Oj_nTGcgopDdkPiVz3GqfRh4',
    appId: '1:168985423795:web:f0e6f55f62c9b5d6de65c6',
    messagingSenderId: '168985423795',
    projectId: 'instagram-9acb0',
    authDomain: 'instagram-9acb0.firebaseapp.com',
    storageBucket: 'instagram-9acb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgWV7ZuSAPHLDbgewVJyBB8sOZONizBRg',
    appId: '1:168985423795:android:8063f2e30df28195de65c6',
    messagingSenderId: '168985423795',
    projectId: 'instagram-9acb0',
    storageBucket: 'instagram-9acb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe_ePykqe25o_Yeu9HXpH_YhBMtBhTLN4',
    appId: '1:168985423795:ios:93c14ec152b84381de65c6',
    messagingSenderId: '168985423795',
    projectId: 'instagram-9acb0',
    storageBucket: 'instagram-9acb0.firebasestorage.app',
    iosBundleId: 'com.ratedsoltech.instaClone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe_ePykqe25o_Yeu9HXpH_YhBMtBhTLN4',
    appId: '1:168985423795:ios:93c14ec152b84381de65c6',
    messagingSenderId: '168985423795',
    projectId: 'instagram-9acb0',
    storageBucket: 'instagram-9acb0.firebasestorage.app',
    iosBundleId: 'com.ratedsoltech.instaClone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADoRho8Z8Oj_nTGcgopDdkPiVz3GqfRh4',
    appId: '1:168985423795:web:ef92b160224c788dde65c6',
    messagingSenderId: '168985423795',
    projectId: 'instagram-9acb0',
    authDomain: 'instagram-9acb0.firebaseapp.com',
    storageBucket: 'instagram-9acb0.firebasestorage.app',
  );
}
